-- =====================================================
-- FIX ALL TEACHERS - Complete Section Assignment
-- Generated by fix-all-teachers-complete.js
-- =====================================================

BEGIN;

-- John (SD ABDI SISWA BINTARO, SD BHAKTI)
-- Grades: 1
-- Current: 6 classes -> New: 8 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 A', '1 B', '1C', '1D', 'KELAS 1 A', 'KELAS 1 B', 'KELAS 1 C', 'KELAS 1 D'],
    updated_at = NOW()
WHERE id = 'c278a88c-0bbe-4193-a379-5c1398878921';

-- Mr Gavin (TK ABDI SISWA BINTARO, SD TARAKANITA, SD ABDI SISWA BINTARO)
-- Grades: 1, 2, 3, 4, 6, TK
-- Current: 13 classes -> New: 41 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 A', '1 B', '1C', '1D', '2 B', '2 C', '2A', '2D', '3A', '3B', '3C', '3D', '4A', '4B', '4C', '4D', '6A', '6B', '6C', '6D', 'KELAS 1 A', 'KELAS 1 C', 'KELAS 1 D', 'KELAS 1B', 'KELAS 2A', 'KELAS 2B', 'KELAS 2C', 'KELAS 2D', 'KELAS 3A', 'KELAS 3B', 'KELAS 3C', 'KELAS 3D', 'KELAS 4A', 'KELAS 4B', 'KELAS 4C', 'KELAS 4D', 'KELAS 6A', 'KELAS 6B', 'KELAS 6C', 'KELAS 6D', 'TK BILINGUAL'],
    updated_at = NOW()
WHERE id = 'a918df6b-12e8-4e03-84f5-3b94fa565b42';

-- Mr Jim (SD CHARITAS JKT)
-- Grades: 1, 2, 3, 5
-- Current: 10 classes -> New: 15 classes
UPDATE profiles
SET assigned_classes = ARRAY['1A', '1B', '1C', '2A', '2B', '2C', '3A', '3B', '3C', '5A', '5B', '5C', 'KELAS 2 C BILINGUAL', 'KELAS 3C BILINGUAL', 'KELAS 5C BILINGUAL'],
    updated_at = NOW()
WHERE id = 'b6fec186-0eb5-48b4-b211-59952418e0b5';

-- Mr Mo (SD ABDI SISWA BINTARO, SD TARAKANITA, SMP TARAKANITA)
-- Grades: 2, 3, 4, 5, 7, 8, 9
-- Current: 33 classes -> New: 45 classes
UPDATE profiles
SET assigned_classes = ARRAY['2 B', '2 C', '2A', '2D', '3A', '3B', '3C', '3D', '4A', '4B', '4C', '4D', '5A', '5B', '5C', '5D', 'KELAS 2A', 'KELAS 2B', 'KELAS 2C', 'KELAS 2D', 'KELAS 3A', 'KELAS 3B', 'KELAS 3C', 'KELAS 3D', 'KELAS 4A', 'KELAS 4B', 'KELAS 4C', 'KELAS 4D', 'KELAS 5A', 'KELAS 5B', 'KELAS 5C', 'KELAS 5D', 'KELAS 7A', 'KELAS 7B', 'KELAS 7C', 'KELAS 7D', 'KELAS 7E', 'KELAS 8A', 'KELAS 8B', 'KELAS 8C', 'KELAS 8D', 'KELAS 9A', 'KELAS 9B', 'KELAS 9C', 'KELAS 9D'],
    updated_at = NOW()
WHERE id = '0091b3a4-bd6d-4d7f-8814-5960fe3769ec';

-- Mr Ren (SDK SANG TIMUR KARANG TENGAH, SD SANG TIMUR CAKUNG, SMP SANG TIMUR KARANG TENGAH, SD SANG TIMUR KARANG TENGAH, SMP SANG TIMUR CAKUNG)
-- Grades: 1, 7
-- Current: 2 classes -> New: 5 classes
UPDATE profiles
SET assigned_classes = ARRAY['1', '1 BILINGUAL', '7A Bilingual', '7B', '7C'],
    updated_at = NOW()
WHERE id = '42bb8138-2cc1-4630-bf95-8713c996711b';

-- Mr Ron (SD CHARITAS JKT, SMP SANG TIMUR KARANG TENGAH, SD ABDI SISWA BINTARO)
-- Grades: 1, 2, 3, 4, 7, 8, 9
-- Current: 15 classes -> New: 33 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 A', '1 B', '1A', '1B', '1C', '1D', '2 B', '2 C', '2A', '2B', '2C', '2D', '3A', '3B', '3C', '3D', '4A', '4B', '4C', '4D', '7A Bilingual', '7B', '7C', '8A', '8B', '8C', '9A', '9B', '9C', '9D', 'KELAS 2 C BILINGUAL', 'KELAS 3C BILINGUAL', 'KELAS 4C BILINGUAL'],
    updated_at = NOW()
WHERE id = '9b9187ca-b00d-4950-90b7-c2f27ee72ec1';

-- Ms Fercy (SD CHARITAS BATAM, TK CHARITAS BATAM, SMP CHARITAS BATAM)
-- Grades: 1, 2, 3, 4, 5, 6, 7, 8, 9, TK
-- Current: 16 classes -> New: 17 classes
UPDATE profiles
SET assigned_classes = ARRAY['KB', 'KELAS 1A', 'KELAS 2A', 'KELAS 2B', 'KELAS 3A', 'KELAS 3B', 'KELAS 4A', 'KELAS 5A', 'KELAS 6A', 'KELAS 6B', 'KELAS 7A', 'KELAS 8A', 'KELAS 8B', 'KELAS 9A', 'KELAS 9B', 'TK A', 'TK B'],
    updated_at = NOW()
WHERE id = 'f2684a45-7b1f-4e64-b08e-6729cfdc4c8d';

-- Ms Lyn (TK KRISTOFORUS 1, TK KRISTOFORUS 2, SD ABDI SISWA ARIES, SMP ABDI SISWA ARIES)
-- Grades: 1, 2, 3, 5, 6, 8, 9, TK
-- Current: 29 classes -> New: 32 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 BILINGUAL', '1 BILINGUAL (Bilingual)', '1A', '1B', '2 BILINGUAL', '2 BILINGUAL (Bilingual)', '2A', '2B', '3A', '3B', '5A', '5B', '6A', '6B', '6C', 'KB', 'KB-1', 'KB-2', 'KELAS 8A', 'KELAS 8B', 'KELAS 9A', 'TK A-1', 'TK A-2', 'TK A2', 'TK B-1', 'TK B-2', 'TK B-3', 'TK B1', 'TK B2', 'TK B3', 'TK B4', 'TK-A1'],
    updated_at = NOW()
WHERE id = '2a5dd696-5fd7-46f7-bce9-8661cad050a8';

-- Ms Maria (SD ABDI SISWA BINTARO)
-- Grades: 1, 2, 3, 4
-- Current: 7 classes -> New: 16 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 A', '1 B', '1C', '1D', '2 B', '2 C', '2A', '2D', '3A', '3B', '3C', '3D', '4A', '4B', '4C', '4D'],
    updated_at = NOW()
WHERE id = '5baaa8d6-d604-4e2c-a706-42aea9caaac2';

-- Ms Rose (SD ABDI SISWA ARIES, SMP ABDI SISWA ARIES, SD ALBERTUS)
-- Grades: 1, 2, 4, 7, 8
-- Current: 8 classes -> New: 14 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 BILINGUAL', '1 BILINGUAL (Bilingual)', '1A', '1B', '2 BILINGUAL', '2 BILINGUAL (Bilingual)', '2A', '2B', '4A', '4B', 'KELAS 7B', 'KELAS 8A', 'KELAS 8B', 'kelas 7 A'],
    updated_at = NOW()
WHERE id = 'ca4841d8-06b3-4a1e-81b7-9ec56fae7d95';

-- Ms Smitha (TK ABDI SISWA BINTARO, SD ABDI SISWA BINTARO)
-- Grades: 1, 2, 3, 4, 6, TK
-- Current: 15 classes -> New: 21 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 A', '1 B', '1C', '1D', '2 B', '2 C', '2A', '2D', '3A', '3B', '3C', '3D', '4A', '4B', '4C', '4D', '6A', '6B', '6C', '6D', 'TK BILINGUAL'],
    updated_at = NOW()
WHERE id = '291e38ed-4de7-4b4f-a8c6-d2507e409e14';

-- Ms. Isabella (SD ABDI SISWA ARIES)
-- Grades: 1, 2
-- Current: 4 classes -> New: 8 classes
UPDATE profiles
SET assigned_classes = ARRAY['1 BILINGUAL', '1 BILINGUAL (Bilingual)', '1A', '1B', '2 BILINGUAL', '2 BILINGUAL (Bilingual)', '2A', '2B'],
    updated_at = NOW()
WHERE id = 'ad8068d9-cbdf-4f3d-9e34-8c7ddf1a4f9f';

-- =====================================================
-- Total: 12 teachers updated
-- =====================================================

-- Verify changes
SELECT name, array_length(assigned_classes, 1) as class_count
FROM profiles
WHERE id IN (
    'c278a88c-0bbe-4193-a379-5c1398878921',  -- John
    'a918df6b-12e8-4e03-84f5-3b94fa565b42',  -- Mr Gavin
    'b6fec186-0eb5-48b4-b211-59952418e0b5',  -- Mr Jim
    '0091b3a4-bd6d-4d7f-8814-5960fe3769ec',  -- Mr Mo
    '42bb8138-2cc1-4630-bf95-8713c996711b',  -- Mr Ren
    '9b9187ca-b00d-4950-90b7-c2f27ee72ec1',  -- Mr Ron
    'f2684a45-7b1f-4e64-b08e-6729cfdc4c8d',  -- Ms Fercy
    '2a5dd696-5fd7-46f7-bce9-8661cad050a8',  -- Ms Lyn
    '5baaa8d6-d604-4e2c-a706-42aea9caaac2',  -- Ms Maria
    'ca4841d8-06b3-4a1e-81b7-9ec56fae7d95',  -- Ms Rose
    '291e38ed-4de7-4b4f-a8c6-d2507e409e14',  -- Ms Smitha
    'ad8068d9-cbdf-4f3d-9e34-8c7ddf1a4f9f'   -- Ms. Isabella
)
ORDER BY name;

COMMIT;
